# Sample workflow for building and deploying a mdBook site to GitHub Pages

name: Deploy mdBook site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MDBOOK_VERSION: 0.4.51
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build custom preprocessor (Rust crate in preprocessors/)
        run: |
          cd preprocessors
          cargo build --release

      - name: Install mdBook
        run: |
          curl --proto '=https' --tlsv1.2 https://sh.rustup.rs  -sSf | sh -s -- -y
          source "$HOME/.cargo/env"
          rustup update
          cargo install --version ${MDBOOK_VERSION} mdbook

          # Установка дополнительных препроцессоров
          cargo install mdbook-admonish@1.18.0
          cargo install mdbook-embedify@0.2.11
          cargo install mdbook-mermaid@0.14.1
          cargo install mdbook-numeq@0.4.0
          cargo install mdbook-katex@0.9.2

      - name: Link local preprocessor
        run: |
          source "$HOME/.cargo/env"
          cd preprocessors
          cargo build --release

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with mdBook
        run: |
          source "$HOME/.cargo/env"
          mdbook build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./book

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4